name: Java CI

on: [push]

jobs:
  build:
 
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: olafurpg/setup-scala@v2
    - name: Build with SBT
      run: ./sbt clean coverage test coverageReport
